name = "TensorKitManifolds"
uuid = "11fa318c-39cb-4a83-b1ed-cdc7ba1e3684"
authors = ["Jutho Haegeman"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"

[compat]
TensorKit = "0.3.0"
Strided = "0.3.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
