name = "TensorKitIsometries"
uuid = "c146d51d-e3d6-4b92-b900-dec265c03167"
authors = ["Jutho Haegeman <jutho.haegeman@ugent.be>"]
version = "0.1.0"

[deps]
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[compat]
TensorKit = "0.3.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
